name: pr-deploy-surge

on:
  pull_request:
    branches:
        - master

jobs:
  console-for-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: github event_path
      run: echo "${{github.event_path}}"
    - name: github event
      run: echo "${{github.event}}" 
    - name: github actor
      run: echo "${{github.actor}}" 
    - name: github head_ref
      run: echo "${{github.head_ref}}" 
      
  build-for-dinesh:
    if: github.actor=='dinskid'
    name: Deploy for PR by Dinesh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./build https://iiittd.surge.sh/ --token 89ac349e161844094bf34748d3188563

  build-for-sarathchandra:
    if: github.actor=='saratchandraogirala'
    name: Deploy for PR by Saratchandraogirala
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./build https://iiitts.surge.sh/ --token 0e7062b67249bd482aa7d80b26e43238
      
  build-for-fahad:
    if: github.actor=='fahad-israr'
    name: Deploy for PR by Fahad Israr
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./build https://iiittf.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
