name: pr-deploy-surge-printer

on:
  pull_request:
    branches:
        - master

jobs:
      
  build-for-dinesh:
    if: github.actor=='dinskid'
    name: Deploy for PR by Dinesh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./build https://iiittdv.surge.sh/ --token ${{secrets.TOKEN}}

  build-for-sarathchandra:
    if: github.actor=='saratchandraogirala'
    name: Deploy for PR by Saratchandraogirala
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./build https://iiittss.surge.sh/ --token ${{secrets.TOKEN}}
      
  build-for-fahad:
    if: github.actor=='fahad-israr'
    name: Deploy for PR by Fahad Israr
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./build https://iiittf.surge.sh/ --token ${{secrets.TOKEN}}
